import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const userSchema = new mongoose.Schema({
    email: {
        type: String,
        required: [true, 'Email is required'],
        unique: true,
        lowercase: true,
        trim: true,
        match: [/^\S+@\S+\.\S+$/, 'Please provide a valid email']
    },
    password: {
        type: String,
        required: [true, 'Password is required'],
        minlength: [8, 'Password must be at least 8 characters'],
        select: false // prevents password from being returned in queries by default
    },
    role: {
        type: String,
        enum: ['admin', 'member'],
        default: 'admin'
    },
    firstName: {
        type: String,
        trim: true
    },
    lastName: {
        type: String,
        trim: true
    },
    isActive: {
        type: Boolean,
        default: true
    },
    lastLogin: {
        type: Date
    }
}, { 
    timestamps: true 
});

// pre save hook hashes password before saving
// meaning that a plain password is never stored in the database
// its hashed instance is stored instead
userSchema.pre('save', async function(next) {
    // Only hash if password is modified
    if (!this.isModified('password')) {
        return next();
    }
    
    const salt = await bcrypt.genSalt(10);
    this.password = await bcrypt.hash(this.password, salt);
    next();
});

// compares this inputted password to hashed password in DB
userSchema.methods.comparePassword = async function(candidatePassword) {
    return await bcrypt.compare(candidatePassword, this.password);
};

// genrerates jwt token for authentication
// how this works is that when user logs in or registers
// a jwt token is generated by using sign to encode user info with a secret key
// this token is then sent to the client to be stored (usually in local storage or cookies)
// on subsequent requests to protected routes, the client sends this token in the authorization header
// the server then verifies the token using the same secret key
// if valid, the server allows access to the protected resource
userSchema.methods.generateAuthToken = function() {
    return jwt.sign(
        {
            id: this._id,
            email: this.email,
            role: this.role
        },
        process.env.JWT_SECRET,
        { expiresIn: process.env.JWT_EXPIRE }
    );
};

const User = mongoose.model('User', userSchema);

export default User;